#pragma once

enum OPTION
{
  OPT_DRAW_TREES = 0,
  OPT_ANIMATE_WATER,
  OPT_DRAW_DEBUG_TEXT,
  OPT_RECREATE_TERRAIN_REQUEST,
  OPT_SAVE_REQUEST,
  OPT_LOAD_REQUEST,
  OPT_SHOW_CURSOR,
  OPT_DRAW_BUILDABLE,
  OPT_HILLS_CULLING,
  OPT_WATER_CULLING,
  OPT_USE_MULTISAMPLING,
  OPT_USE_SHADOWS,
  OPT_DRAW_LAND,
  OPT_DRAW_WATER,
  OPT_MODELS_LAND_BLENDING,
  OPT_MODELS_PHONG_SHADING,
  OPT_POLYGON_LINE,
  OPT_DEBUG_RENDER,
  OPT_SHADOW_CAMERA_FIXED,
  OPT_USE_SHADOW_CAMERA_MATRIX,
  OPT_CSM_VISUALIZATION,
  OPT_FRUSTUM_VISUALIZATION,
  OPT_EXPECTED_VOLUME_VISUALIZATION,
  OPT_ACTUAL_VOLUME_VISUALIZATION,
  OPT_USE_DOF,
  OPT_GRASS_SHADOW,
  OPT_SHOW_VRAM_AVAILABLE,
  OPTIONS_COUNT
};
