#ifndef TEXTUREUNITS_H
#define TEXTUREUNITS_H

enum TEXTURE_UNITS
{
  TEX_FLAT = 0,
  TEX_FLAT_2 = 1,
  TEX_FLAT_x2 = 2,
  TEX_FLAT_2_x2 = 3,
  TEX_DIFFUSE_MIX_MAP = 4,
  TEX_HILL = 5,
  TEX_HILL_2 = 6,
  TEX_HILL_SPECULAR = 7,
  TEX_SHORE = 8,
  TEX_SHORE_2 = 9,
  TEX_UNDERWATER_RELIEF = 10,
  TEX_SKYBOX = 11,
  TEX_FRAME_MULTISAMPLED = 12,
  TEX_FRAME = 13,
  TEX_FRAME_HDR = 14,
  TEX_DEPTH_MAP_SUN = 15,
  TEX_FONT = 16,
  TEX_TERRAIN_NORMAL = 17,
  TEX_WATER_NORMAL = 18,
  TEX_WATER_SPECULAR = 19,
  TEX_UNDERWATER_DIFFUSE = 20
};

#endif // TEXTUREUNITS_H
