#ifndef TEXTUREUNITS_H
#define TEXTUREUNITS_H

enum TEXTURE_UNITS
{
  TEX_LAND = 0,
  TEX_LAND_2,
  TEX_DIFFUSE_MIX_MAP,
  TEX_TERRAIN_NORMAL,
  TEX_WATER_NORMAL,
  TEX_WATER_SPECULAR,
  TEX_WATER_DUDV,
  TEX_HILL,
  TEX_HILL_2,
  TEX_HILL_SPECULAR,
  TEX_SHORE,
  TEX_SHORE_2,
  TEX_UNDERWATER_DIFFUSE,
  TEX_UNDERWATER_RELIEF,
  TEX_SKYBOX_HILLS_NEAR,
  TEX_SKYBOX_HILLS_NEAR_NORMAL,
  TEX_SKYBOX_HILLS_FAR,
  TEX_SKYBOX_HILLS_FAR_NORMAL,
  TEX_SKYBOX_CLOUDS,
  TEX_THE_SUN,
  TEX_THE_SUN_ENVIRONMENT_LIGHT,
  TEX_THE_SKY,
  TEX_FRAME_MULTISAMPLED,
  TEX_FRAME,
  TEX_FRAME_HDR,
  TEX_FRAME_DEPTH,
  TEX_FRAME_VIGNETTE,
  TEX_FRAME_WATER_REFLECTION,
  TEX_FRAME_WATER_REFRACTION,
  TEX_FRAME_WATER_REFRACTION_DEPTH,
  TEX_DEPTH_MAP_SUN,
  TEX_FONT,
  TEXTURE_UNITS_SIZE
};

#endif // TEXTUREUNITS_H
