#ifndef SHADERUNITS_H
#define SHADERUNITS_H

enum SHADER
{
  SHADER_HILLS_CULLING = 0,
  SHADER_HILLS,
  SHADER_HILLS_NORMALS,
  SHADER_SHORE,
  SHADER_SHORE_NORMALS,
  SHADER_UNDERWATER,
  SHADER_LAND,
  SHADER_WATER_CULLING,
  SHADER_WATER,
  SHADER_WATER_NORMALS,
  SHADER_SKYBOX,
  SHADER_SUN,
  SHADER_MODELS_GOURAUD,
  SHADER_MODELS_PHONG,
  SHADER_FONT,
  SHADER_COORDINATE_SYSTEM,
  SHADER_BUILDABLE,
  SHADER_SELECTED,
  SHADER_MS_TO_DEFAULT,
  SHADER_SHADOW_TERRAIN,
  SHADER_SHADOW_MODELS,
  SHADER_FRUSTUM
};

#endif // SHADERUNITS_H
