#ifndef TEXTUREUNITS_H
#define TEXTUREUNITS_H

enum TEXTURE_UNITS
{
  TEX_LAND = 0,
  TEX_LAND_2,
  TEX_LAND_x2,
  TEX_LAND_2_x2,
  TEX_HILL,
  TEX_HILL_2,
  TEX_HILL_SPECULAR,
  TEX_SHORE,
  TEX_SHORE_2,
  TEX_WATER_NORMAL,
  TEX_WATER_SPECULAR,
  TEX_UNDERWATER_DIFFUSE,
  TEX_UNDERWATER_RELIEF,
  TEX_SKYBOX,
  TEX_MESH_SPECULAR,
  TEX_MESH_DIFFUSE,
  TEX_FRAME_MULTISAMPLED,
  TEX_FRAME,
  TEX_FRAME_HDR,
  TEX_DEPTH_MAP_SUN,
  TEX_FONT,
  TEX_TERRAIN_NORMAL,
  TEX_DIFFUSE_MIX_MAP
};

#endif // TEXTUREUNITS_H
