#ifndef TEXTUREUNITS_H
#define TEXTUREUNITS_H

enum TEXTURE_UNITS
{
  TEX_LAND = 0,
  TEX_LAND_2,
  TEX_HILL,
  TEX_HILL_2,
  TEX_HILL_SPECULAR,
  TEX_SHORE,
  TEX_SHORE_2,
  TEX_WATER_NORMAL,
  TEX_WATER_SPECULAR,
  TEX_WATER_DUDV,
  TEX_UNDERWATER_DIFFUSE,
  TEX_UNDERWATER_RELIEF,
  TEX_SKYBOX,
  TEX_SKYBOX_NORMAL,
  TEX_SKYBOX_FAR,
  TEX_SKYBOX_FAR_NORMAL,
  TEX_SKYBOX_SKY,
  TEX_THE_SUN,
  TEX_FRAME_MULTISAMPLED,
  TEX_FRAME,
  TEX_FRAME_HDR,
  TEX_FRAME_DEPTH,
  TEX_FRAME_VIGNETTE,
  TEX_FRAME_WATER_REFLECTION,
  TEX_DEPTH_MAP_SUN,
  TEX_FONT,
  TEX_TERRAIN_NORMAL,
  TEX_DIFFUSE_MIX_MAP,
  TEX_LENS_FLARE1,
  TEX_LENS_FLARE2,
  TEX_LENS_FLARE3,
  TEX_LENS_FLARE4,
  TEX_LENS_FLARE5,
  TEX_LENS_FLARE6,
  TEX_LENS_FLARE7,
  TEXTURE_UNITS_SIZE
};

#endif // TEXTUREUNITS_H
